DirectoryPath: "public"
CheckExternal: false
CheckInternal: true
CheckInternalHash: true
CheckImages: true
CheckScripts: true
CheckMeta: false
EnforceHTTPS: false
IgnoreAltMissing: true
IgnoreURLs:
  - "^https?://"
TestFileIgnorePatterns:
  - "^tmp/"
